FROM ubuntu:latest
MAINTAINER Ben Sheffield (bshefb@gmail.com)

RUN mkdir /go
RUN mkdir /go/src
RUN mkdir /go/pkg
RUN mkdir /go/bin

ENV GOPATH /go

RUN apt-get update
RUN apt-get install cmake golang python git -y
RUN git clone --depth=1 https://github.com/llvm-mirror/llvm /go/src/llvm.org/llvm
RUN sh /go/src/llvm.org/llvm/bindings/go/build.sh -DCMAKE_BUILD_TYPE=Debug -DLLVM_TARGETS_TO_BUILD=host -DBUILD_SHARED_LIBS=ON

CMD ls $GOPATH/src/llvm.org/llvm