// Code generated by "stringer -type=TokenType"; DO NOT EDIT

package lexer

import "fmt"

const _TokenType_name = "IDENTNUMBERFLOATTRUEFALSETYPEINT32FLOAT32RETURNIFELSEFORRANGEARROWINFERASSIGNDOUBLECOLONINCREMENTDECREMENTEQUALNOTEQUALCOMMANSEMICOLONNEWLINEOPENBODYCLOSEBODYOPENBRACKETCLOSEBRACKETPLUSMINUSMULTIPLYFLOATDIVIDEINTDIVIDELESSTHANMORETHANCOLONASSIGNBANG"

var _TokenType_index = [...]uint8{0, 5, 11, 16, 20, 25, 29, 34, 41, 47, 49, 53, 56, 61, 66, 77, 88, 97, 106, 111, 119, 125, 134, 141, 149, 158, 169, 181, 185, 190, 198, 209, 218, 226, 234, 239, 245, 249}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
